CoreMVC/CoreMVC/CoreMVC/ViewModels/CarsListViewModel.cs
using CoreMVC.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMVC.ViewModels
{
	public class CarsListViewModel
	{
		public IEnumerable<Car> AllCars { get; set; }

		public string CurrCategory { get; set; }
	}
}

CoreMVC/CoreMVC/CoreMVC/ViewModels/HomeViewModel.cs
using CoreMVC.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMVC.ViewModels
{
	public class HomeViewModel
	{
		public IEnumerable<Car> FavCars { get; set; }
	}
}

CoreMVC/CoreMVC/CoreMVC/ViewModels/SellCartViewModel.cs
using CoreMVC.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMVC.ViewModels
{
	public class SellCartViewModel
	{
		public SellCart SellCart { get; set; }

		public OrderDetail OrderDetail { get; set; }
	}
}

CoreMVC/CoreMVC/CoreMVC/Controllers/CarsController.cs
using CoreMVC.Data.Interfaces;
using CoreMVC.Data.Models;
using CoreMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMVC.Controllers
{
	public class CarsController : Controller
	{
		private readonly IAllCars _allCars;
		private readonly ICarsCategory _allCatgories;

		public CarsController(IAllCars allCars, ICarsCategory allCatigories)
		{
			_allCars = allCars;
			_allCatgories = allCatigories;
		}

		[Route("Cars/ListCars")]
		[Route("Cars/ListCars/{category}")]
		public ViewResult ListCars(string category)
		{
			string _category = category;
			string _currCategory = "";

			IEnumerable<Car> cars = null;

			if(string.IsNullOrEmpty(_category))
			{
				cars = _allCars.Cars.OrderBy(i => i.Id);
			}
			else
			{
				int currCatId = _allCatgories.AllCategories.Where(i => i.CategoryName.Contains(_category)).First().Id;
				cars = _allCars.Cars.Where(i => i.CategoryId == currCatId);

				if(currCatId == 1)
				{
					_currCategory = "Electric cars:";
				}
				else if(currCatId == 2)
				{
					_currCategory = "Cars with internal combustion engine:";
				}
				
			}
			
			ViewBag.Title = "Page with cars";

			var obj = new CarsListViewModel()
			{
				AllCars = cars,
				CurrCategory = _currCategory
			};			
			
			return View(obj);
		}
	}
}

CoreMVC/CoreMVC/CoreMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreMVC.Data.Interfaces;
using CoreMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CoreMVC.Controllers
{
    public class HomeController : Controller
    {
		private IAllCars _carRepository;

		public HomeController(IAllCars carRepository)
		{
			_carRepository = carRepository;
		}

        public IActionResult Index()
        {
			var homeCars = new HomeViewModel
			{
				FavCars = _carRepository.GetFavCars
			};
            return View(homeCars);
        }
    }
}

CoreMVC/CoreMVC/CoreMVC/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreMVC.Data.Interfaces;
using CoreMVC.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreMVC.Controllers
{
    public class OrderController : Controller
    {
		private readonly IAllOrders _allOrders;
		private readonly SellCart _sellCart;

		public OrderController(IAllOrders allOrders, SellCart sellCart)
		{
			_allOrders = allOrders;
			_sellCart = sellCart;
		}

		[HttpGet]
		public IActionResult CheckOut()
		{
			_sellCart.ListSellItems = _sellCart.GetSellItems();
			if (_sellCart.ListSellItems.Count == 0)
			{
				ModelState.AddModelError("", "Cart is empty!");
				return RedirectToAction("NotComplete");
			}
			return View();
		}

		[HttpPost]
		public IActionResult CheckOut(Order order)
		{
			_sellCart.ListSellItems = _sellCart.GetSellItems();

			if (ModelState.IsValid) 
			{
				_allOrders.CreateOrder(order);
				return RedirectToAction("Complete");
			}

			return View(order);
		}

		public IActionResult Complete()
		{
			ViewBag.Message = "Order is complete.";
			return View();
		}

		public IActionResult NotComplete()
		{
			ViewBag.Message = "Cart is empty!";
			return View();
		}
	}
}

CoreMVC/CoreMVC/CoreMVC/Controllers/SellCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreMVC.Data.Interfaces;
using CoreMVC.Data.Models;
using CoreMVC.Data.Repository;
using CoreMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CoreMVC.Controllers
{
    public class SellCartController : Controller
    {
		private readonly IAllCars _carRepository;
		private readonly SellCart _sellCart;

		public SellCartController(IAllCars carRepository, SellCart sellCart)
		{
			_carRepository = carRepository;
			_sellCart = sellCart;
		}


        public IActionResult Index()
        {
			var items = _sellCart.GetSellItems();
			_sellCart.ListSellItems = items;

			var obj = new SellCartViewModel
			{
				SellCart = _sellCart
			};

            return View(obj);
        }

		public RedirectToActionResult AddToCart(int id)
		{
			var item = _carRepository.Cars.FirstOrDefault(i => i.Id == id);
			if (item != null)
			{
				_sellCart.AddToCart(item);
			}
			return RedirectToAction("Index");
		}
    }
} 

CoreMVC/CoreMVC/CoreMVC/Views/Cars/ListCars.cshtml
<div class="container-fluid h-100">
    <div class="row align-items-center h-100">
        <div class="col-sm-12">
            <div class="row justify-content-center">
                <div class="col-12 text-center">
                     <h3>@Model.CurrCategory</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mt-5 mb-2">

    @{
        foreach (Car car in Model.AllCars)
        {
            @Html.Partial("AllCars", car)
          
        }
    }

</div>

CoreMVC/CoreMVC/CoreMVC/Views/Home/Index.cshtml
@model HomeViewModel

<div class="container-fluid h-100">
    <div class="row align-items-center h-100">
        <div class="col-sm-12">
            <div class="row justify-content-center">
                <div class="col-4 text-center">
                    <h1> Best cars: </h1>
                  </div>
            </div>
        </div>
    </div>
</div>
<div class="row mt-5 mb-2">

    @{
        foreach (Car car in Model.FavCars)
        {
            @Html.Partial("AllCars", car)

        }
    }

</div>

CoreMVC/CoreMVC/CoreMVC/Views/Order/CheckOut.cshtml
@model Order

<h3> Making an order</h3>
        <div class="row">
            <form asp- action="CheckOut" method="post" class="form-horizontal">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <div class="col-md-50">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="SurName"></label>
                    <div class="col-md-50">
                        <input asp-for="SurName" class="form-control" />
                        <span asp-validation-for="SurName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Adress"></label>
                    <div class="col-md-50">
                        <input asp-for="Adress" class="form-control" />
                        <span asp-validation-for="Adress" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="EMail"></label>
                    <div class="col-md-50">
                        <input asp-for="EMail" class="form-control" />
                        <span asp-validation-for="EMail" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Phone"></label>
                    <div class="col-md-50">
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                </div>
                <input class="btn btn-success" type="submit" value="Making an order" />
            </form>
        </div>

CoreMVC/CoreMVC/CoreMVC/Views/Order/Complete.cshtml
<div class="container-fluid h-100">
<div class="row align-items-center h-100">
    <div class="col-sm-12">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <h5>@ViewBag.Message </h5> <a href="/">Return</a>
            </div>
        </div>
    </div>
</div>
</div>

CoreMVC/CoreMVC/CoreMVC/Views/Order/NotComplete.cshtml
<div class="container-fluid h-100">
    <div class="row align-items-center h-100">
        <div class="col-sm-12">
            <div class="row justify-content-center">
                <div class="col-12 text-center">
                    <h5>@ViewBag.Message</h5> <a href="/">Please select a product.</a>
                </div>
            </div>
        </div>
    </div>
</div>

CoreMVC/CoreMVC/CoreMVC/Views/SellCart/Index.cshtml
@model SellCartViewModel
<div class="container">
    @foreach (var el in Model.SellCart.ListSellItems)
    {
    <div class="alert alert-warning mt-3">
        <b>Car:</b>@el.Car.Name<br/>
        <b>Price:</b> @el.Car.Price.ToString()$
    </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="CheckOut">Payment</a>
</div>

CoreMVC/CoreMVC/CoreMVC/Views/Shared/AllCars.cshtml
@model Car

<div class="container">
    <div class="row">
        <div class="col">
            <div class="col-sm">
                <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name">
            </div>
        </div>
        <div class="col">
            <h3>@Model.Name</h3>
            <div class="row">
                @Model.ShortDesc
            </div>
            <div class="row">
                @Model.LongDesc
            </div>
            <div class="row">
                @Model.Category.CategoryName
            </div>
            <div class="row">
                @Model.Price.ToString()$
            </div>
            <div class="row">
                <a class="btn btn-outline-success" asp-controller="SellCart" asp-action="AddToCart" asp-route-Id="@Model.Id">Add to cart</a>
            </div>
        </div>
        
    </div>
    <div class="row">
        <div class="col-xs-6" style="height: 5px;">
           
        </div>
    </div>   
</div>

CoreMVC/CoreMVC/CoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css"/>

    <nav class="navbar navbar-expand-lg">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Main<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Cars/ListCars/Electric car">Electro</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="/Cars/ListCars/Car with internal combustion engine">Fuel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/SellCart/">Cart</a>
                </li>
            </ul>
        </div>
    </nav>

</head>

<body>
   <div class="container body-content">
        @RenderBody()
        <script src=" ~/js/bootstrap.js" rel="stylesheet" type="text/css">
        </script>
        <footer>
            <div class="container-fluid h-100">
                <div class="row align-items-center h-100">
                    <div class="col-sm-12">
                        <div class="row justify-content-center">
                            <div class="col-4 text-center">
                                <p>© 2020 - CarStore. <a href="#">All rights reserved.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

</body>

</html>